### ISSUE TITLE
Use local database instead of Firebase

### ISSUE THREAD

**Issue by rayad** [salvadordeveloper/TikTok-Flutter#1]
Hi,

First of all you have done a great job to creating this as i have found many TikTok UI clone but they are just using background image.
You have created a complete project.

I am struggling to use this with my local database which is MySql.

Also i didn't found much documentation for this. Youtube video was also smaller. 

Can you put some documentations or help to implement it with other database instead of Firebase.

**Comment by salvadordeveloper** [comment]
Hi! Thanks for being interested in the project.
First, you can implement MySql but you need to know how to use it because
it is not possible to connect directly to Mysql from flutter, you need to
create an API server, can be NodeJS, Laravel or whatever you prefer. And
then you simply make the request from the app(You also need to know how to
make an HTTP request in flutter.
As you say I do not publish a tutorial or something similar is only a demo
of the project and the source code, i'm currently working to add more
features to the app.
Really there are a lot of tutorials on how to use MySql with Flutter, it is
not hard to implement.

**Comment by rayad** [comment]
Thanks for the update. I will be waiting for newest version. 
I am using MySQL and WAMP server with Flutter but haven't used BLOC pattern in the past. I am still working on your API code. So that I can incorporate it. 

My other modules are almost ready now just need to work on video play thing.

**Comment by SivaramNalliboyana** [comment]
Hello how did you connect to mysql, I cant do it. Is there any packagae

**Comment by digitpk** [comment]
Maybe this will help you.
https://pub.dev/packages/mysql1
