### ISSUE TITLE
Out Of Memory Exception when scrolling through many videos

### ISSUE THREAD

**Issue by massanu** [salvadordeveloper/TikTok-Flutter#11]
Hey man I believe your project is quite amazing, I have been having fun with it for the past few days.

One issue I cannot fix at all, I am getting out of memory exception when scrolling through many videos, I have been trying to find a way to dispose the video controller without success

I see that you have tried also, did you manage to solve that issue somehow ?

Thanks !

**Comment by MadhavVij** [comment]
@salvadordeveloper Are you still working on the project? I am having the same issue of out of memory.
I guess it's because you are not disposing controller. I know you are having difficulties with IOS and controller disposal. Can you point me to a commit which had the disposer implemented so I can test it on Android?

Thanks again! This is a great proj. and I bet took a lot of effort :)
